##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.0.0] date: [Wed Feb 13 14:07:15 CST 2019]
##########################################################################################################################

# C sources
STM32F4xx_SOURCES :=  \
$(HW_LIB)/Src/main.c \
$(HW_LIB)/Src/gpio.c \
$(HW_LIB)/Src/adc.c \
$(HW_LIB)/Src/i2c.c \
$(HW_LIB)/Src/iwdg.c \
$(HW_LIB)/Src/tim.c \
$(HW_LIB)/Src/usart.c \
$(HW_LIB)/Src/wwdg.c \
$(HW_LIB)/Src/stm32f4xx_it.c \
$(HW_LIB)/Src/stm32f4xx_hal_msp.c \
$(HW_LIB)/Src/system_stm32f4xx.c  

#C_SOURCES = $(STM32F4xx_SOURCES)

CMSIS_DIR      := $(HW_LIB)/Drivers/CMSIS
STDPERIPH_DIR   = $(HW_LIB)/Drivers/STM32F4xx_HAL_Driver
STDPERIPH_SRC   = $(notdir $(wildcard $(STDPERIPH_DIR)/Src/*.c))
STDPERIPH_SRC2   = $(addprefix $(STDPERIPH_DIR)/Src/,$(STDPERIPH_SRC))
EXCLUDES        =

C_SOURCES += $(STDPERIPH_SRC2)
VPATH       := $(VPATH):$(STDPERIPH_DIR)/Src

# ASM sources
ASM_SOURCES +=  \
$(HW_LIB)/startup_stm32f407xx.s

#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32F407xx

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-I$(HW_LIB)/Inc \
-I$(HW_LIB)/Drivers/STM32F4xx_HAL_Driver/Inc \
-I$(HW_LIB)/Drivers/STM32F4xx_HAL_Driver/Inc/Legacy \
-I$(HW_LIB)/Drivers/CMSIS/Device/ST/STM32F4xx/Include \
-I$(HW_LIB)/Drivers/CMSIS/Include \
-I$(HW_LIB)/Drivers/CMSIS/Include


# *** EOF ***