##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.0.0] date: [Wed Feb 13 13:46:35 CST 2019]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################

######################################
# source
######################################
# C sources
STM32L0xx_SOURCES =  \
$(HW_LIB)/Src/main.c \
$(HW_LIB)/Src/gpio.c \
$(HW_LIB)/Src/i2c.c \
$(HW_LIB)/Src/usart.c \
$(HW_LIB)/Src/usb_device.c \
$(HW_LIB)/Src/usbd_conf.c \
$(HW_LIB)/Src/usbd_desc.c \
$(HW_LIB)/Src/usbd_cdc_if.c \
$(HW_LIB)/Src/stm32l0xx_it.c \
$(HW_LIB)/Src/stm32l0xx_hal_msp.c \
$(HW_LIB)/Src/system_stm32l0xx.c \
$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c  

#C_SOURCES += $(STM32L0xx_SOURCES)

CMSIS_DIR      := $(HW_LIB)/Drivers/CMSIS
STDPERIPH_DIR   = $(HW_LIB)/Drivers/STM32L0xx_HAL_Driver
STDPERIPH_SRC   = $(notdir $(wildcard $(STDPERIPH_DIR)/Src/*.c))
STDPERIPH_SRC2   = $(addprefix $(STDPERIPH_DIR)/Src/,$(STDPERIPH_SRC))
EXCLUDES        =

C_SOURCES += $(STDPERIPH_SRC2)
VPATH       := $(VPATH):$(STDPERIPH_DIR)/Src

# ASM sources
ASM_SOURCES +=  \
$(HW_LIB)/startup_stm32l052xx.s
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m0plus

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32L052xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-I$(HW_LIB)/Inc \
-I$(HW_LIB)/Drivers/STM32L0xx_HAL_Driver/Inc \
-I$(HW_LIB)/Drivers/STM32L0xx_HAL_Driver/Inc/Legacy \
-I$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Core/Inc \
-I$(HW_LIB)/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-I$(HW_LIB)/Drivers/CMSIS/Device/ST/STM32L0xx/Include \
-I$(HW_LIB)/Drivers/CMSIS/Include \
-I$(HW_LIB)/Drivers/CMSIS/Include

# *** EOF ***